#!/bin/bash
# Build script for the Quarto website

set -e

# Extract evaluation data from PDFs before rendering
if ! command -v Rscript &> /dev/null; then
  echo "Rscript is required to build this site because Quarto renders R code in evals.qmd." >&2
  exit 1
fi

if ! command -v pdftotext &> /dev/null; then
  echo "pdftotext is required to extract evaluation data from PDFs." >&2
  echo "Install it with: sudo apt-get install -y poppler-utils (Debian/Ubuntu)" >&2
  echo "                 brew install poppler (macOS)" >&2
  exit 1
fi

echo "Extracting evaluation data from PDFs..."
Rscript data/build_evals_data.R

echo "Rendering Quarto website..."
quarto render

echo "Copying additional resources..."
# Copy .nojekyll for GitHub Pages
cp .nojekyll docs/

# Copy CV file
mkdir -p docs/files/CV
cp static/files/CV/Morrison_CV.pdf docs/files/CV/

# Copy eval files
mkdir -p docs/files/evals
cp static/files/evals/*.pdf docs/files/evals/

echo "Writing redirects for transferred project sites..."
# See redirects.tsv. Each <path> gets a docs/<path>/index.html that
# forwards to the new site; docs/redirects.js (loaded by 404.html)
# forwards deeper paths under <path>/ to the same page on the new site.
{
  echo "// Generated by build.sh from redirects.tsv"
  echo "(function () {"
  echo "  var redirects = {"
} > docs/redirects.js
while IFS=$'\t' read -r path target; do
  case "$path" in ''|'#'*) continue ;; esac
  mkdir -p "docs/$path"
  cat > "docs/$path/index.html" <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Moved to $target</title>
<link rel="canonical" href="$target">
<meta name="robots" content="noindex">
<meta http-equiv="refresh" content="0; url=$target">
<script>location.replace("$target" + location.search + location.hash);</script>
</head>
<body>
<p>This site has moved to <a href="$target">$target</a>.</p>
</body>
</html>
HTML
  echo "    \"$path\": \"$target\"," >> docs/redirects.js
done < redirects.tsv
cat >> docs/redirects.js <<'JS'
  };
  var m = location.pathname.match(/^\/([^\/]+)(?:\/(.*))?$/);
  if (m && Object.prototype.hasOwnProperty.call(redirects, m[1])) {
    location.replace(redirects[m[1]] + (m[2] || "") + location.search + location.hash);
  }
})();
JS

echo "Build complete! Website is ready in docs/"
