// Generated by build.sh from redirects.tsv
(function () {
  var redirects = {
    "rme": "https://morrison-lab.github.io/rme/",
    "cie": "https://morrison-lab.github.io/cie/",
    "psw": "https://morrison-lab.github.io/psw/",
    "qbt": "https://morrison-lab.github.io/qbt/",
    "qwt": "https://morrison-lab.github.io/qwt/",
    "qmt": "https://morrison-lab.github.io/qmt/",
    "rpt": "https://morrison-lab.github.io/rpt/",
    "wai": "https://morrison-lab.github.io/wai/",
    "gha": "https://morrison-lab.github.io/gha/",
    "ai-config": "https://morrison-lab.github.io/ai-config/",
  };
  var m = location.pathname.match(/^\/([^\/]+)(?:\/(.*))?$/);
  if (m && Object.prototype.hasOwnProperty.call(redirects, m[1])) {
    location.replace(redirects[m[1]] + (m[2] || "") + location.search + location.hash);
  }
})();
